name: Flutter Web Preview

on:
  push:
    branches:
      - main

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"

      - name: Create Flutter Project
        run: flutter create app

      - name: Copy Source
        run: |
          cp -r lib app/
          cp pubspec.yaml app/

      - name: Build Web
        run: |
          cd app
          flutter pub get
          flutter build web

      - name: Upload Web Preview
        uses: actions/upload-artifact@v4
        with:
          name: WOG-Web
          path: app/build/web
