name: Flutter Debug APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"

      - name: Create Flutter Project
        run: flutter create app

      - name: Copy Source Code
        run: |
          cp -r lib app/
          cp pubspec.yaml app/

      - name: Get Packages
        run: |
          cd app
          flutter pub get

      - name: Build Debug APK
        run: |
          cd app
          flutter build apk --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: WOG-Debug-APK
          path: app/build/app/outputs/flutter-apk/app-debug.apk
